version: '3.7'

services:

  # Strapi - Content Manage System (CMS)
  strapi:
    image: heg0dmsk/strapi:4.0.0-alpine
    container_name: strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: dbName
      DATABASE_HOST: StrapiPostgresHostname
      DATABASE_PORT: 5432
      DATABASE_USERNAME: dbUsername
      DATABASE_PASSWORD: dbPassword
      NODE_ENV: development
      TZ: Europe/Berlin
    volumes:
      - ./strapi_data:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - StrapiPostgresHostname
    networks:
      - strapi

  # Postgres Database for Strapi CMS
  StrapiPostgresHostname:
    image: postgres:14-alpine
    container_name: strapi-postgres
    environment:
      POSTGRES_DB: dbName
      POSTGRES_USER: dbUsername
      POSTGRES_PASSWORD: dbPassword
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - strapi

networks:
  strapi:
