name: Build And Push Container Images

on:
  push:
    branches:
      - main
    paths:
      - strapi.version
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build And Push Docker Images
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Get strapi version
        id: strapi
        run: |
          echo ::set-output name=version::$(< strapi.version)
      -  
        name: Get node version
        id: node
        run: |
          echo ::set-output name=version::$(< node.version)
      -  
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Log in to GitHub Package Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}   
      -                                                                                                                                                                                                                                             
        id: build
        run: docker build -t heg0dmsk/strapi:${{ steps.strapi.outputs.version }}-alpine -t heg0dmsk/strapi:latest -t ghcr.io/heg0dmsk/strapi:${{ steps.strapi.outputs.version }}-alpine -t ghcr.io/heg0dmsk/strapi:latest --build-arg NODE_VERSION=${{ steps.node.outputs.version }} --build-arg STRAPI_VERSION=${{ steps.strapi.outputs.version }} . 
        shell: bash
      - 
        id: push-container-images-to-dockerhub
        run: docker image push --all-tags heg0dmsk/strapi
        shell: bash
      -
        id: push-container-images-to-ghcr
        run: docker image push --all-tags ghcr.io/heg0dmsk/strapi
        shell: bash
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
