name: Update webhook

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
  workflow_dispatch:

jobs:
  update-webhook:
    name: Update strapi version
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Fetch latest strapi release
        id: strapi
        run: |
          echo ::set-output name=release_tag::$(curl -sL https://api.github.com/repos/strapi/strapi/releases/latest | jq -r ".tag_name")
          echo ::set-output name=current_tag::$(< strapi.version)
      - 
        name: Update strapi version
        if: steps.strapi.outputs.current_tag != steps.strapi.outputs.release_tag
        run: |
          echo ${{ steps.strapi.outputs.release_tag }} > strapi.version
      - 
        name: Create pull request
        if: steps.strapi.outputs.current_tag != steps.strapi.outputs.release_tag
        uses: peter-evans/create-pull-request@v4
        with:
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: Update strapi from ${{ steps.strapi.outputs.current_tag }} to ${{ steps.strapi.outputs.release_tag }}
          title: Update strapi from ${{ steps.strapi.outputs.current_tag }} to ${{ steps.strapi.outputs.release_tag }}
          body: |
            Updates [strapi/strapi](https://github.com/strapi/strapi) from ${{ steps.strapi.outputs.current_tag }} to ${{ steps.strapi.outputs.release_tag }}
          labels: |
            🛶 upstream
            🤖 bot
          branch: strapi/strapi-${{ steps.strapi.outputs.release_tag }}
          delete-branch: true
